server:
  port: 80

spring:
  application:
    name: ms-gateway
  cloud:
    gateway:
      discovery:
        locator:
          lower-case-service-id: true # 将服务名称转小写
          enabled: true # 开启配置注册中心进行路由的功能
      routes:
        - id: ms-diners
          uri: lb://ms-diners
          predicates:
            - Path=/diners/**
          filters:
            - StripPrefix=1   # 分割处理，只路由后半部分

        - id: ms-oauth2-server
          uri: lb://ms-oauth2-server
          predicates:
            - Path=/auth/**
          filters:
            - StripPrefix=1



      secure:
        ignore:
          urls: # 配置白名单路径，需要放行的路径
            - /actuator/**
            - /auth/oauth/**
            - /diners/signin
            - /diners/send
            - /diners/checkPhone
            - /diners/register
            - /seckill/add
            - /restaurants/**





eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
  client:
    service-url:
      defaultZone: http://localhost:8080/eureka/